### ISSUE TITLE
Fix felfire and shadow embrace item triggers

### ISSUE THREAD

**Issue by aaronma37** [Zarant/WoW_Hardcore#293]

**Comment by athramp** [comment]
Era Server: Hydraxian Waterlords
Nick: Athramp
Achievement Attempted: Felfire
Achievement failed due to usage of Faintly Glowing Skull, which clearly is allowed according to achievement rules
I have no screenshots as I only just realized I failed the challange, I've used it in Skull Rock fighting Gazzuz and the elite, a heated moment, didn't notice the alert.
Hardcore_Character = {
	["grief_warning_conditions"] = 3,
	["guid"] = "Player-5275-016D6463",
	["time_tracked"] = 37172,
	["dt"] = {
		["repeated_runs"] = 0,
		["legacy_runs_imported"] = true,
		["pending"] = {
		},
		["runs"] = {
		},
		["warn_infractions"] = true,
		["version"] = 2,
		["current"] = {
		},
		["overleveled_runs"] = 0,
	},
	["time_played"] = 37183,
	["kill_list_dict"] = {
		["Gazz'uz"] = 1,
	},
	["hardcore_player_name"] = "",
	["team"] = {
	},
	["converted_successfully"] = false,
	["tracked_played_percentage"] = 99.83863593577709,
	["game_version"] = "Era",
	["accumulated_time_diff"] = 11,
	["converted_time"] = "",
	["trade_partners"] = {
	},
	["bubble_hearth_incidents"] = {
	},
	["deaths"] = {
	},
	["passive_achievements"] = {
	},
	["played_time_gap_warnings"] = {
	},
	["sacrificed_at"] = "",
	["achievements"] = {
		"ImpMaster", -- [1]
	},
	["first_recorded"] = 1674767975,
	["party_mode"] = "Solo",
	["adjusted_time10"] = 12048,
}
GreenWall = {
	["created"] = "2023-01-25 13:17:23",
	["log"] = false,
	["debug"] = 0,
	["joindelay"] = 30,
	["verbose"] = false,
	["updated"] = "2023-01-25 13:17:23",
	["roster"] = true,
	["logsize"] = 2048,
	["version"] = "0.11.7",
	["redact"] = true,
	["ochat"] = false,
	["tag"] = true,
}
GreenWallMeta = {
	["updated"] = "2023-01-26 22:20:23",
	["mode"] = "account",
	["version"] = "0.11.7",
	["created"] = "2023-01-25 13:17:23",
}
GreenWallLog = {
}
