### ISSUE TITLE
Bug: /played results are being spammed

### ISSUE THREAD

**Issue by zdeyn** [Zarant/WoW_Hardcore#40]
This happened 6 or so times over the space of a few minutes:

![image](https://user-images.githubusercontent.com/79044233/140013645-2e3c5055-b2a0-4769-8369-3aed2d1c02fc.png)

**Comment by aaronma37** [comment]
Root cause of this is that when we request for the played time, it comes back in batches.  The mutex that we use to hide these messages doesn't hide these messages when they come in batches.  The first one will be hidden and subsequent ones will not. 

Possible COAs:
1) Decrease our C_TIMER rate.  This will lower the chance that we get batches of played time back
2) Implement a buffer (see PR).  This will allow us to handle batches but we should also be careful with this otherwise the player won't be able to /played and see their played time.  If we have a max_buffer length it shouldn't be an issue though

**Comment by RobertB4** [comment]
Thanks for looking into this! I think the easiest solution is to stop caching the time played and only request it when we need it (before generating the verification string).

**Comment by PedsDad** [comment]
Same issue.  causing some lock ups for me and resulted in a death when it locked up. 
![Uploading WoWScrnShot_111021_002832.jpg…]()

**Comment by RobertB4** [comment]
@PedsDad 
> Same issue. causing some lock ups for me and resulted in a death when it locked up.
Thanks for reporting this problem!
Can you try to upload the screenshot again? Github takes a few seconds to upload your image. Once uploaded, it will show similar to an html <img> tag iirc.

Just to confirm, by lock up you mean your screen froze?

**Comment by PedsDad** [comment]
Yes, I have periods where it freezes or skips.  Sometimes I get long strings of the messages. It has happened on log in, but usually it's random during play.  when I disabled the add on, the issue went away.  
![WoWScrnShot_111021_002832](https://user-images.githubusercontent.com/94038751/141091462-71c5a4b4-2550-4299-8a11-0dedff383d63.jpg)

**Comment by blenderer** [comment]
@PedsDad What kind of machine are you running WoW on? Also do you have video of the lag? Kind of hard to diagnose this with just a screenshot

**Comment by PedsDad** [comment]
No I wish I did.  I'm on a Dell G5 laptop right now.  It's main machine I play on.  I'll run some video tomorrow and see if it happens again at all.

**Comment by blenderer** [comment]
@PedsDad also try deleting your saved_variable for Hardcore addon.
1. Exit game completely
2. Delete `{WOW_INSTALL_DIRECTORY}\_classic_era\WTF\Account\{ACCOUNT_ID or ACCOUNT_NAME}\{SERVER_NAME}\{CHARACTER_NAME}\SavedVariables\Hardcore.lua
`

**Comment by 1010101110** [comment]
#58
