### ISSUE TITLE
Thoughts on the Addon security

### ISSUE THREAD

**Issue by Rioos** [Zarant/WoW_Hardcore#495]
.

**Comment by random415** [comment]
If it weren't for the add-on and the hardcore community there would be no official servers on the horizon; I am extremely grateful for the hard work and steadfast advocacy by everyone involved.

If permanent death is problematic due to time investment or attachment to your character you can still do the solo self found challenge on a regular classic era server, turn off trades, don't use auction house, etc.

I believe there are free character transfers over to Mankrik if you have died on BSB and want to continue the solo self found aspect of the challenge. You don't need an add-on to do this.

That being said, I would assume people have been doing this for a while now:

1. First edit WTF > Account > Account Number > Server > Dead Character > SavedVariables > Hardcore.lua
2. Change deaths:
```
	["deaths"] = {
		{
			["player_alive_trigger"] = "06/15/23 11:52:37",
			["player_dead_trigger"] = "06/15/23 11:52:31",
		}, -- [1]
	},
```
```
	["deaths"] = {
	},
```
3. Change verification status:
```
	["verification_status"] = "FAIL",
```
```
	["verification_status"] = "PASS",
```
4. Change verification details:
```
	["verification_details"] = "(deaths=1)",
```
```
	["verification_details"] = "(deaths=0)",
```
5. Edit Interface > AddOns > Hardcore > Security.lua
6. Change Hardcore_VerifyChecksum()
```
-- Do a check of the checksum
function Hardcore_VerifyChecksum()
	if WARNING == nil or WARNING == "" then 
		Hardcore_InsertModificationWarning()
	elseif Hardcore_Character ~= nil then
		local the_checksum = Hardcore_CalculateChecksum()
		local tampered = false
		if Hardcore_Character["checksum"] == nil then
			tampered = true
		elseif Hardcore_Character["checksum"] ~= the_checksum then
			tampered = true
		end
		if tampered == true then
			Hardcore:Print( "You have tampered with the data file -- your run is now invalid!")
			Hardcore:Print( "The Hardcore mods will be notified.")
			-- Make sure the warning is displayed again!
			WARNING = "-- " .. WARNING_MESSAGE .. " ---"
			tampered_status = true
		else
			Hardcore:Print( "Data file integrity okay")
		end
	end
end
```
```
-- Do a check of the checksum
function Hardcore_VerifyChecksum()
	if WARNING == nil or WARNING == "" then 
		Hardcore_InsertModificationWarning()
	elseif Hardcore_Character ~= nil then
		local the_checksum = Hardcore_CalculateChecksum()
		local tampered = false
	        Hardcore:Print( "Data file integrity okay")
	end
end
```
7. Group with immortals and use petrification flasks
8. Wait for PTR and official servers to ensure deaths are permanent

I know I'm probably missing a few necessary changes, making changes out of order, or including something redundant but this took me 5-10 minutes using string search in vim.

When inspecting another player for their verification status the death log is utilized, no?

**Comment by frankdj100** [comment]
Thanks for your insights, gentlemen, but this is not the best place  to discuss vulnerabilities.
