### ISSUE TITLE
Forsaken are referred to in verify tab as "Scourge"

### ISSUE THREAD

**Issue by random415** [Zarant/WoW_Hardcore#497]
I noticed that forsaken were referred to in the verify tab as scourge. They are not scourge according to the lore of the Warcraft universe as they are not beholden to the Lich King.

Where can I change this myself?

<img width="1046" alt="Screenshot 2023-06-13 at 2 07 04 PM" src="https://github.com/Zarant/WoW_Hardcore/assets/134174490/99d01b05-d981-49f2-8c12-b710abb8ba62">

**Comment by thread53** [comment]
This is related to how the results from `GetPlayerInfoByGUID` API are passed. Instead of using "localizedRace", to set character's race, it uses "englishRace", which for "Undead" returns "Scourge".

Sources:
https://wowpedia.fandom.com/wiki/API_GetPlayerInfoByGUID
https://wowwiki-archive.fandom.com/wiki/API_UnitRace

**Comment by aaronma37** [comment]
fixed
